#!/bin/bash
echo "Manual Verification Steps:"
echo ""
echo "1. Open a markdown file in Neovim:"
echo "   nvim test/fixtures/sample.md"
echo ""
echo "2. Test commands manually:"
echo "   :MarkedPreviewOpen     - Should open Marked 2"
echo "   :MarkedPreviewStart    - Should start watching"
echo "   :MarkedPreviewUpdate   - Should update preview"
echo "   :MarkedPreviewStop     - Should stop watching"
echo ""
echo "3. Verify automatic updates:"
echo "   - Start watching with :MarkedPreviewStart"
echo "   - Make changes to the buffer"
echo "   - Check if Marked 2 updates automatically (with debounce)"
echo ""
echo "4. Test configuration:"
echo "   :lua require('marked-preview').setup({debounce_delay = 1000})"
echo ""
echo "Note: Marked 2 must be installed for full integration testing."